AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'spec/**/*'

####################################
## Customization for this project ##
####################################

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Metrics/MethodLength:
  Max: 12
