AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'spec/**/*'

####################################
## Customization for this project ##
####################################

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 12
